#!/usr/bin/python3
#
# get-chat-id.py - Find your Telegram chat_id and set up credentials
# 
# Steps:
#   1. Create a bot via @BotFather on Telegram → get TOKEN
#   2. Send any message to your new bot on Telegram
#   3. Run: python3 get-chat-id.py --token YOUR_TOKEN_HERE
#   4. Script prints your chat_id and saves ~/.copilot-telegram
#

import sys
import os
import urllib.request
import json
import argparse

VERSION = "1.0.0"
CREDENTIALS_FILE = os.path.expanduser("~/.copilot-telegram")


## Utils

def get_updates(token):
    url = f"https://api.telegram.org/bot{token}/getUpdates"
    try:
        with urllib.request.urlopen(url, timeout=10) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"ERROR: HTTP {e.code} - {body}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def save_credentials(token, chat_id):
    content = f"""# Copilot Telegram Notify - credentials
# Generated by get-chat-id.py
# DO NOT commit this file!

TELEGRAM_BOT_TOKEN={token}
TELEGRAM_CHAT_ID={chat_id}
"""
    with open(CREDENTIALS_FILE, "w") as f:
        f.write(content)
    os.chmod(CREDENTIALS_FILE, 0o600)
    print(f"Credentials saved to {CREDENTIALS_FILE} (mode 600)")


## Main

def main():
    parser = argparse.ArgumentParser(
        description=f"Find your Telegram chat_id and save credentials v{VERSION}",
        epilog="Steps: (1) Create bot via @BotFather → get TOKEN  "
               "(2) Send any message to your bot  "
               "(3) Run this script with --token YOUR_TOKEN"
    )
    parser.add_argument("--token", required=True, help="Telegram bot token from @BotFather")
    parser.add_argument("--save", action="store_true", default=True, help="Save credentials to ~/.copilot-telegram (default: true)")
    parser.add_argument("--no-save", action="store_true", help="Only print chat_id, do not save")
    args = parser.parse_args()

    token = args.token.strip()
    print(f"Fetching updates for bot token: {token[:15]}...")
    
    data = get_updates(token)
    
    if not data.get("ok"):
        print(f"ERROR: Telegram API returned not OK: {data}", file=sys.stderr)
        sys.exit(1)
    
    results = data.get("result", [])
    if not results:
        print("No messages found.")
        print("\nMake sure you sent a message to your bot first, then run this script again.")
        print(f"Open Telegram, find your bot, and send any message (e.g. /start)")
        sys.exit(1)
    
    # Collect unique senders
    seen = {}
    for update in results:
        msg = update.get("message") or update.get("channel_post")
        if not msg:
            continue
        chat = msg.get("chat", {})
        cid = chat.get("id")
        name = chat.get("first_name") or chat.get("title") or chat.get("username") or "Unknown"
        uname = chat.get("username", "")
        if cid and cid not in seen:
            seen[cid] = {"name": name, "username": uname, "type": chat.get("type", "?")}
    
    if not seen:
        print("No chat messages found in updates.")
        print("Send a message directly to your bot and retry.")
        sys.exit(1)
    
    print(f"\nFound {len(seen)} chat(s):\n")
    chosen_id = None
    for cid, info in seen.items():
        uname = f" (@{info['username']})" if info["username"] else ""
        print(f"  chat_id: {cid}  |  {info['name']}{uname}  |  type: {info['type']}")
        if info["type"] == "private":
            chosen_id = cid
    
    if not chosen_id:
        chosen_id = list(seen.keys())[0]
    
    print(f"\nSelected chat_id: {chosen_id}")
    
    if not args.no_save:
        save_credentials(token, chosen_id)
        print(f"\nTest it with:")
        print(f"  python3 notify.py 'Hello from Copilot!'")


main()
